### ISSUE TITLE
Can't buy inverse teleporter if the terminaITP command is on TRUE

### ISSUE THREAD

**Issue by Zuploader** [darmuh/TerminalStuff#11]
Found a new bug, you can't buy it from the store if you have the command enable in the config, maybe it's the same probleme with the normal teleporter, gonna test it

**Comment by darmuh** [comment]
So I just tested this myself a bit and it looks like there's a conflict between typing "inverse" to buy the inverse teleporter and using "inverse" to use the inverse teleporter. Which is I think what you were saying the bug is?

You can still buy the inverse teleporter if you type anything other than just "inverse" either via typing a portion of the word (example: "inver") or typing the word teleporter (in full or a portion of it) after inverse. 

Also, another workaround is typing "buy inverse" which is what I've just done in my current session.

Either way, I still don't like the conflict so I will probably use this issue with the command as an opportunity for trying to define custom keywords for commands in the config and allow for replacing the word "inverse" with whatever you want.

**Comment by Zuploader** [comment]
Even if you type inverse teleporter it doesn't work, i didn't tryed the other keyword i just disabled the inverse tp part in cfg file

**Comment by darmuh** [comment]
My mistake, just checked and you're absolutely right. I did however confirm if you type "inver" it will allow you to buy the inverse teleporter. Same with "buy inverse" as I mentioned before. Definitely an issue with overlapping keywords between my mod and vanilla base-game. 

In the next patch i'll at the very least take out the "inverse" keyword and replace it with something else (if not allow for a keyword defined in the config). I think I may also look for a way to detect if the inverse teleporter has been purchased and add the keywords then, rather than at the start of the game.

**Comment by darmuh** [comment]
Have this issue fixed in my dev version that im working on. Basically reworked the command so that the keywords are only added AFTER each item has been bought. So if you try tp or itp it will not be a valid command until you have a teleporter of the type needed to run the command

**Comment by darmuh** [comment]
Fix should be in the latest update (2.1.0)
