### ISSUE TITLE
Invalid command resets view

### ISSUE THREAD

**Issue by Sp1rit** [darmuh/TerminalStuff#17]
Switching the player while in minicams now works. As soon as you enter an invalid command the view resets though.

Did you miss the code in your commit? It only shows the readme as changed in 2.2?

**Comment by darmuh** [comment]
> Switching the player while in minicams now works. As soon as you enter an invalid command the view resets though.
> 
> Did you miss the code in your commit? It only shows the readme as changed in 2.2?

ooo yikes, yea the last couple updates have been a pain to update github. That should be fixed now.

As for the invalid command reset issue, are you playing with the camsNeverHide setting enabled or disabled?

With it enabled you shouldn't be experiencing this issue but disabled I think this issue was "intended". I should be able to add invalid commands to the list of possible resulting events that does not hide any cams elements.

**Comment by darmuh** [comment]
Patched this in 2.2.1, thanks for the bug report!
