### ISSUE TITLE
Double backslash in custom ASCII

### ISSUE THREAD

**Issue by jacket430** [darmuh/TerminalStuff#29]
Hey there,

I've been trying to get some custom ascii working but it's been pretty difficult to make something without two backslashes "\\" as it causes one of them to get deleted. And by that I mean it actually deletes the first backslash from the cfg. It also makes it so if you have something like \\r\n, it'll cause it to show up as "\r" and then a new line because of the \n in game. weirdly enough it deletes one of the \ but the \r still doesn't work. Possibly on reboot, but at least it doesn't when you open try the first time. 

If there's anything I can do to stop it from deleting a backslash I would love to know. 

Thanks!

**Comment by darmuh** [comment]
so essentially what you are modifying is the direct string of that portion of the home page when modifying the ascii art.

The reason you are only getting one \ is because special characters in strings are preceded by a \ in strings.

You can read more about it here - https://www.w3schools.com/cs/cs_strings_chars.php

So, if you want a double backslash or \\, you'll need to actually use 3 or \\\.

if you'd like, I can create something similar to the [leadingSpace] placeholder I created for my default ascii art which will replace any instance of "[leadingSpace]" in the config value with the space value that I originally wanted (had to do this because bepinex removes leading spaces from config items). So I could make something like [doubleSlash] and anywhere in your ascii art where there is two slashes you'd replace it with that.

As for \r\n, i'm not sure why it would show \r in it's regular text form. Logically speaking it should work the same way as any other text item where \r\n is used to note a new line. That said, I don't think there's much a difference between \r\n and just \n

**Comment by darmuh** [comment]
here's the applicable part of my code if you'd like to see it in action

https://github.com/darmuh/TerminalStuff/blob/781f4e5d379fe242d0e2e70b8b883cbe1c46007a/DarmuhsTerminalCommands/MyTerminalPatcher.cs#L201

**Comment by jacket430** [comment]
Ahh, interesting! I think I got it from that link you shared, it might be worth noting in the config somehow, or on a wiki somewhere. Thanks a bunch!
