### ISSUE TITLE
[Feat] Inverse Teleporter command

### ISSUE THREAD

**Issue by jacobmix** [darmuh/TerminalStuff#3]
A command for the Inverse Teleporter would be nice since there's already one for the normal teleporter.
Inverse Teleporter/Inverse/Inverse TP/ITP or such probably. As long as it doesn't conflict with the store if it can. (You have to buy it first after all)

**Comment by darmuh** [comment]
definitely do-able, only reason I didn't before was because I figured most people would not want to be in the terminal when pressing the inverse tp button. 

Speaking of store conflicts, I may update the current tp command to not accept teleporter if it is conflicting with the store. Thanks for the reminder.

<Adding to work list>

**Comment by jacobmix** [comment]
I mean the command doesn't activate the teleporter since it isn't there, and you can't buy the teleporter when you have it. So i think it'll work fine. Except if it overwrites the teleporter shop command entirely or something. 
I don't think it'll try to buy the inverse teleporter either. But haven't tested it. Thanks for your work so far btw.

**Comment by darmuh** [comment]
oh yea that makes sense, prob no conflicts then.

I can probably add an inversetp in my next update alongside some other command additions.
Currently looking into changing flashlight color

**Comment by darmuh** [comment]
got this working in my dev version. should work with either "inverse" or "itp" 

Will push it next patch 👍
