### ISSUE TITLE
The way to not replace View Monitor command (Question)

### ISSUE THREAD

**Issue by SleepyMiles** [darmuh/TerminalStuff#34]
Hello I just use this mod and I really wonder is there any way not to replace the view monitor command? because I personally don't like map command because the map keep disappear when I use other commands such as store, scan etc. and I really like the slowly startup animation of view monitor command

**Comment by darmuh** [comment]
Hello, 

If you want to restore the vanilla "view monitor" command please disable the following config items:
![image](https://github.com/user-attachments/assets/72542164-8d3c-4896-a7d8-8cb31c3470dc)

They can be found in the "Extra Commands (On/Off)" Section.

Unfortunately vanilla view monitor does not play nice with those commands, which is why vanilla view monitor is disabled when any of those are enabled.


Also, if your only issue is that the map disappears when you use other commands you can enable this setting.

![image](https://github.com/user-attachments/assets/e8715625-f46b-4597-8c83-3bf995208f8c)
(found in Extras Configuration Section)

The map command is considered a "cams-type" view

**Comment by darmuh** [comment]
Please also note that the vanilla view monitor is not compatible with networkedNodes (synced terminal view)

**Comment by SleepyMiles** [comment]
Thank you so much! :D
